server {
    listen 80;
    listen [::]:80;
    server_name _;

    gzip on;
    gzip_disable "msie6";
    gzip_proxied any;
    gzip_types text/plain text/html text/xml text/css text/javascript application/json application/javascript application/x-javascript application/xml application/xml+rss;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        default_type "text/html";
        try_files $uri $uri.html $uri/index.html =404;
        expires 1d;
        add_header Cache-Control "public";
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
    }
}
